import Hotelguru.models.Hotel
import Hotelguru.models.Room
import Hotelguru.models.Role
import Hotelguru.models.User
import Hotelguru.models.Service
import Hotelguru.models.Reservation
import Hotelguru.models.ReservationService
import Hotelguru.models.ReservationRoom
import Hotelguru.models.Invoice
import Hotelguru.models.InvoiceItem
import Hotelguru.models.RoomStatus