"""empty message

Revision ID: 695d404fb511
Revises: 
Create Date: 2026-03-08 20:31:14.137277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695d404fb511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=30), nullable=False),
    sa.Column('City', sa.String(length=30), nullable=False),
    sa.Column('Addres', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=30), nullable=False),
    sa.Column('Email', sa.String(length=30), nullable=False),
    sa.Column('Password', sa.String(length=30), nullable=False),
    sa.Column('Phone', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Number', sa.Integer(), nullable=False),
    sa.Column('Beds', sa.Integer(), nullable=False),
    sa.Column('Kitchen', sa.Boolean(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userroles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userroles')
    op.drop_table('rooms')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('hotels')
    # ### end Alembic commands ###
