"""empty message

Revision ID: 93d1360379d4
Revises: 695d404fb511
Create Date: 2026-03-08 21:38:26.736423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d1360379d4'
down_revision = '695d404fb511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Address', sa.String(length=30), nullable=False))
        batch_op.drop_column('Addres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Addres', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('Address')

    # ### end Alembic commands ###
